-- Time-boxed visitor log for the public demo entry points (/demo, /demo-coop, /odi), added
-- 2026-09-30 so the ODI review period's visitors can be counted past nginx's 14-day log rotation.
--
-- Every demo visitor signs in as the same shared demo account, so the app can't tell them apart.
-- Each row stores a keyed one-way hash of (IP + browser user-agent), never the address itself:
-- stable for one visitor across visits (so repeat visitors show up) but not reversible without the
-- key. The key lives only in demo_visit_key and is generated by the server on first use.
--
-- Retention: rows older than 30 days are deleted by the server (matches the privacy policy's
-- "server logs are retained for up to 30 days"). Logging stops by itself on 2026-10-14
-- (DEMO_VISIT_TRACKING_UNTIL in server/server.js); drop both tables when the review period is over.

CREATE TABLE IF NOT EXISTS demo_visit_key (
  id  smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  key text NOT NULL
);

CREATE TABLE IF NOT EXISTS demo_visit_log (
  id            bigserial PRIMARY KEY,
  visited_at    timestamptz NOT NULL DEFAULT now(),
  entry         text NOT NULL CHECK (entry IN ('demo', 'demo-coop', 'odi')),
  visitor_hash  text NOT NULL,
  referrer_host text,
  is_bot        boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_demo_visit_log_visited ON demo_visit_log (visited_at DESC);
CREATE INDEX IF NOT EXISTS idx_demo_visit_log_visitor ON demo_visit_log (visitor_hash);

GRANT SELECT, INSERT ON demo_visit_key TO causal_app;
GRANT SELECT, INSERT, DELETE ON demo_visit_log TO causal_app;
GRANT USAGE ON SEQUENCE demo_visit_log_id_seq TO causal_app;
