'use strict';

const { fiscalYearForDate, getFiscalYearEndMonth } = require('./fiscalYear');
const { recalcScheduleItems } = require('./scheduleRecalc');

/**
 * Cross-FY carryforward for insurance schedule items (Phase 1 of multi-year
 * budget planning — see docs/Causal_Development_Path.md). An insurance
 * policy is the one schedule-item type with a real calendar end date
 * (policy_end_date) that can genuinely cross the org's fiscal-year boundary
 * — everything else (monthly/quarterly/custom items) is bounded to the
 * item's own 12 fiscal months by construction, so only insurance items
 * carry forward automatically.
 *
 * Spawns/updates/removes sibling org_schedule_items rows in fiscal_year+1
 * (and beyond, for multi-year policies) so next year's budget already has
 * the remaining coverage without anyone manually re-entering it. Siblings
 * are marked auto_generated=TRUE until a human edits one directly — once
 * claimed, this function never touches that row again.
 */

async function getOrgFyEndMonth(pool, orgId) {
  const m = await getFiscalYearEndMonth(pool, orgId);
  return m || 12;
}

async function copyAllocations(pool, fromItemId, toItemId) {
  const { rows } = await pool.query(
    `SELECT coop_program_id, percent_bps FROM org_schedule_item_allocations WHERE coop_schedule_item_id=$1`,
    [fromItemId]
  );
  if (!rows.length) return;
  await pool.query(`DELETE FROM org_schedule_item_allocations WHERE coop_schedule_item_id=$1`, [toItemId]);
  for (const a of rows) {
    await pool.query(
      `INSERT INTO org_schedule_item_allocations (coop_schedule_item_id, org_id, coop_program_id, percent_bps)
       SELECT $1, org_id, $2, $3 FROM org_schedule_items WHERE id=$1`,
      [toItemId, a.coop_program_id, a.percent_bps]
    );
  }
}

/**
 * Call after an insurance item is created or its dates/amount/account
 * change. `item` is the full current row from org_schedule_items.
 * Returns the set of fiscal years that were recalculated so the caller can
 * surface them (e.g. to the client, for a "next year updated too" note).
 */
async function syncInsuranceCarryforward(pool, orgId, item) {
  const touchedFYs = new Set();

  // Not an insurance item, or missing dates: clean up any stale auto-generated
  // children from when it may have been one (e.g. schedule_type changed away
  // from 'insurance', or a date was cleared).
  if (item.schedule_type !== 'insurance' || !item.policy_start_date || !item.policy_end_date) {
    const removed = await removeAutoGeneratedChildren(pool, orgId, item.id, 0);
    for (const fy of removed) touchedFYs.add(fy);
    for (const fy of touchedFYs) await recalcScheduleItems(pool, orgId, fy);
    return { touchedFYs: [...touchedFYs] };
  }

  const fyEndMonth = await getOrgFyEndMonth(pool, orgId);
  const lastCoveredFY = fiscalYearForDate(item.policy_end_date, fyEndMonth);

  // Remove any auto-generated children beyond the (possibly shrunk) span.
  const removed = await removeAutoGeneratedChildren(pool, orgId, item.id, lastCoveredFY);
  for (const fy of removed) touchedFYs.add(fy);

  for (let fy = item.fiscal_year + 1; fy <= lastCoveredFY; fy++) {
    const { rows: existingRows } = await pool.query(
      `SELECT id, auto_generated FROM org_schedule_items
       WHERE org_id=$1 AND origin_item_id=$2 AND fiscal_year=$3`,
      [orgId, item.id, fy]
    );
    const existing = existingRows[0] || null;

    if (existing && !existing.auto_generated) {
      // A human has since edited this sibling directly — leave it alone.
      continue;
    }

    let siblingId;
    if (existing) {
      await pool.query(
        `UPDATE org_schedule_items SET
           label=$1, account_id=$2, program_id=$3, grant_id=$4,
           quantity=$5, unit_amount_cents=$6, policy_start_date=$7, policy_end_date=$8,
           named_schedule_id=$9, updated_at=NOW()
         WHERE id=$10`,
        [item.label, item.account_id, item.program_id, item.grant_id,
         item.quantity, item.unit_amount_cents, item.policy_start_date, item.policy_end_date,
         item.named_schedule_id, existing.id]
      );
      siblingId = existing.id;
    } else {
      const { rows } = await pool.query(
        `INSERT INTO org_schedule_items
           (org_id, account_id, program_id, grant_id, named_schedule_id, fiscal_year,
            label, schedule_type, quantity, unit_amount_cents, frequency,
            policy_start_date, policy_end_date, sort_order, origin_item_id, auto_generated)
         VALUES ($1,$2,$3,$4,$5,$6,$7,'insurance',$8,$9,'monthly',$10,$11,$12,$13,TRUE)
         RETURNING id`,
        [orgId, item.account_id, item.program_id, item.grant_id, item.named_schedule_id, fy,
         item.label, item.quantity, item.unit_amount_cents,
         item.policy_start_date, item.policy_end_date, item.sort_order || 0, item.id]
      );
      siblingId = rows[0].id;
    }

    await copyAllocations(pool, item.id, siblingId);
    touchedFYs.add(fy);
  }

  for (const fy of touchedFYs) await recalcScheduleItems(pool, orgId, fy);
  return { touchedFYs: [...touchedFYs] };
}

/**
 * Deletes auto_generated children of `originItemId` whose fiscal_year is
 * beyond `keepThroughFY` (pass 0 to remove all). Returns the distinct
 * fiscal years that had a row removed, so the caller can re-recalc them.
 */
async function removeAutoGeneratedChildren(pool, orgId, originItemId, keepThroughFY) {
  const { rows } = await pool.query(
    `DELETE FROM org_schedule_items
     WHERE org_id=$1 AND origin_item_id=$2 AND fiscal_year > $3 AND auto_generated=TRUE
     RETURNING fiscal_year`,
    [orgId, originItemId, keepThroughFY]
  );
  return [...new Set(rows.map(r => r.fiscal_year))];
}

/**
 * Call when the origin item itself is deleted — removes every
 * auto_generated child regardless of fiscal_year (budget-line cleanup for
 * each child is handled by removeScheduleItemLines, called separately by
 * the route for each removed id).
 */
async function removeAllCarryforwardChildren(pool, orgId, originItemId) {
  const { rows } = await pool.query(
    `SELECT id, fiscal_year FROM org_schedule_items
     WHERE org_id=$1 AND origin_item_id=$2 AND auto_generated=TRUE`,
    [orgId, originItemId]
  );
  return rows;
}

module.exports = { syncInsuranceCarryforward, removeAllCarryforwardChildren, getOrgFyEndMonth };
